const express = require('express');
const router = new express.Router();
const path = require("path");
const multer = require("multer");
const authenticate = require("../middleware/auth");
var fs = require('fs');

const User = require('../models/users');
const { ObjectID } = require('mongodb');

// dictonary with subcategories 
const Categories = {
    "Hombre": ["Camisas", "Camisetas", "Pantalones", "Sweaters y Cardigans", "Bermudas", "Chaquetas y Blazers", "Zapatos", "Buzos", "Jeans", "Accesorios", "Pijamas"],
    "Mujer": ["Blusas", "Zapatos", "Buzos", "Chalecos", "Jeans", "Camisetas", "Pantalones", "Shorts", "Vestidos y Faldas", "Chaquetas y Blazers", "Sweaters y Cardigans", "Accesorios", "Pijamas"],
    "Ninos": ["Camisas", "Camisetas", "Pantalones", "Sweaters y Cardigans", "Bermudas", "Chaquetas y Blazers", "Zapatos", "Buzos", "Jeans", "Accesorios", "Pijamas"],
    "Ninas": ["Blusas", "Zapatos", "Buzos", "Chalecos", "Jeans", "Camisetas", "Pantalones", "Shorts", "Vestidos y Faldas", "Chaquetas y Blazers", "Sweaters y Cardigans", "Accesorios", "Pijamas"], 
    "Bebes": ["Camisas", "Blusas", "Camisetas", "Pantalones", "Sweaters y Cardigans", "Bermudas", "Chaquetas y Blazers", "Zapatos", "Buzos", "Jeans", "Accesorios", "Pijamas ", "Shorts", "Vestidos y Faldas"]
  };
// Image storage
const storage = multer.diskStorage({    
    destination: "./public/images/",
    filename: function(req, file, cb){
       cb(null,"IMAGE-" + Date.now() + path.extname(file.originalname));
    }
});


 const upload = multer({
    storage: storage,
    limits:{fileSize: 1000000000},
 })

 router.post('/upload',upload.single('profilePhoto'), (req, res,next) => {
     console.log(req.get('profilePhoto'));
    console.log(req.file);//this will be automatically set by multer
    console.log(req.body);
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.file.path,(err, contents)=> {
     if (err) {
     res.status(500).send();
    }else{
     var  path = req.file.path
     res.status(201).send({ path })
    }
   });
  });
 
router.post('/prefAssistant', authenticate ,async (req, res) => {
    //find an existing user
    var user = req.user
    console.log(user)
     try {
        user.tokens = user.tokens.filter((token) => {
            return token.token !== req.token
        })
    try {
        user.tokens = user.tokens.filter((token) => {
            return token.token !== req.token
        })
        user.addPreferences(req);
        res.status(201).send(user)
    } catch (error) {
        res.status(500).send();
    }
    } catch (error) {
        res.status(500).send()
    }
})

router.post('/categories' ,async (req, res) => {

        var categories_out = [] 

        if (Boolean(req.body.checked1)) {categories_out =  categories_out.concat(Categories["Hombre"] ) }  
        if (Boolean(req.body.checked2)) {categories_out =  categories_out.concat(Categories["Mujer"]) }
        if (Boolean(req.body.checked3)) {categories_out =  categories_out.concat(Categories["Ninos"]) }
        if (Boolean(req.body.checked4)) {categories_out =  categories_out.concat(Categories["Ninas"]) }
        if (Boolean(req.body.checked5)) {categories_out =  categories_out.concat(Categories["Bebes"]) }
        var out = Array.from( new Set(categories_out))
        console.log(out)
        res.status(201).send({ out })

})  

module.exports = router


